force-app/main/default/objects/SQX_Team_Members__c/SQX_Team_Members__c.object-meta.xml
<CustomObject>
    <description>The team member object will be used to store team members of other objects as well like
Contacts and Cases.</description>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SQX_Team_Members__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>An account can have multiple team members</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SQX_Team_Members__c/fields/Member_Type__c.field-meta.xml
<CustomField>
    <fullName>Member_Type__c</fullName>
    <description>Used to define the type of team member</description>
    <label>Member Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TriggerSetting__c/TriggerSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Use this to make trigger active/inactive</description>
    <label>Trigger Setting</label>
</CustomObject>

force-app/main/default/objects/TriggerSetting__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Field to make trigger active/inactive</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestAccountTrigger.cls
@isTest
public class TestAccountTrigger {
    
    @testSetup
    private static void setup()
    {
        Profile custStandardProfile=[Select Id, Name From Profile where Name='Custom Standard User'];
        List<User> users=new List<User>();
        User testUser = new user(alias = 'test123', email='test123@noemail.com', 
                                 emailencodingkey='UTF-8', firstName='Test', lastname='Compliance', languagelocalekey='en_US',
                                 localesidkey='en_IN', profileid = custStandardProfile.Id, country='India',
                                 timezonesidkey='Asia/Kolkata', username='test_g@noemail.com'); 
        
        User testUserNoAccess = new user(alias = 'test1253', email='test123@noemail.com', 
                                         emailencodingkey='UTF-8', firstName='TestNo', lastname='Compliance', languagelocalekey='en_US',
                                         localesidkey='en_IN', profileid = custStandardProfile.Id, country='India',
                                         timezonesidkey='Asia/Kolkata', username='test_b@noemail.com');
        users.add(testUser);
        users.add(testUserNoAccess);
        insert users;
        
        PermissionSet accountAdmin = [SELECT Id FROM PermissionSet WHERE Name = 'Account_Admin'];
        insert new PermissionSetAssignment(AssigneeId = testUser.id, PermissionSetId = accountAdmin.Id);      
        
    }
    
    @isTest
    private static void testWithHrAndAdminMember()
    {
        User accountAdmin=[Select Id, Name From User where username='test_g@noemail.com'];
        System.runAs(accountAdmin)
        {
            // Account acc=[Select Id, Name, Active__c From Account Where Name='Test'];
            TriggerSetting__c  cs= new TriggerSetting__c();
            cs.Name='AccountTrigger';
            cs.IsActive__c=true;
            insert cs; 
            Account acc=new Account(Name='Test');
            insert acc;
            Test.startTest();    
            List<SQX_Team_Members__c> teamMembers=[Select ID, Member_Type__c FROM SQX_Team_Members__c Where Account__c=:acc.Id ];
            teamMembers[0].Member_Type__c='HR';
            teamMembers[1].Member_Type__c='Admin';
            update teamMembers;
            acc.Active__c='Yes';
            update acc;
            Test.stopTest();
            acc=[Select Id, Name, Active__c From Account Where Name='Test'];
            Assert.areEqual('Yes', acc.Active__c);
        }
    }
    
    @isTest
    private static void testWithOnlyAdminMember()
    {
        User accountAdmin=[Select Id, Name From User where username='test_g@noemail.com'];
        System.runAs(accountAdmin)
        {
            // Account acc=[Select Id, Name, Active__c From Account Where Name='Test'];
            TriggerSetting__c  cs= new TriggerSetting__c();
            cs.Name='AccountTrigger';
            cs.IsActive__c=true;
            insert cs; 
            Account acc=new Account(Name='Test');
            insert acc;
            Test.startTest();    
            List<SQX_Team_Members__c> teamMembers=[Select ID, Member_Type__c FROM SQX_Team_Members__c Where Account__c=:acc.Id ];
            teamMembers[0].Member_Type__c='Admin';
            update teamMembers;
            acc.Active__c='Yes';
            try{
            update acc;
            }
            catch(Exception ex)
            {
              System.debug(ex.getMessage()); 
               Assert.isTrue(ex.getMessage().contains('Accounts can not be activated without team members of HR and Admin member type'));
            }
            Test.stopTest();
        }
    }
    
     @isTest
    private static void testWithoutAccountAdmin()
    {
        User accountAdmin=[Select Id, Name From User where username='test_b@noemail.com'];
        System.runAs(accountAdmin)
        {
            // Account acc=[Select Id, Name, Active__c From Account Where Name='Test'];
            TriggerSetting__c  cs= new TriggerSetting__c();
            cs.Name='AccountTrigger';
            cs.IsActive__c=true;
            insert cs; 
            Account acc=new Account(Name='Test');
            insert acc;
            Test.startTest();    
            List<SQX_Team_Members__c> teamMembers=[Select ID, Member_Type__c FROM SQX_Team_Members__c Where Account__c=:acc.Id ];
            teamMembers[0].Member_Type__c='HR';
            teamMembers[1].Member_Type__c='Admin';
            update teamMembers;
            acc.Active__c='Yes';
            try{
            update acc;
            }
            catch(Exception ex)
            {
              System.debug(ex.getMessage()); 
               Assert.isTrue(ex.getMessage().contains('You don\'t have Account admin permission'));
            }
            Test.stopTest();
        }
    }
    
}